export const products = [
  {
    id: 1,
    name: "Laptop",
    title: "Dell XPS 15",
    description:
      "The Dell XPS 15 is a powerful and sleek laptop designed for professionals who demand performance and style. With its high-resolution display and top-notch specs, it's perfect for multimedia editing, programming, and more.",
    vendor: "Dell",
    in_stock: 50,
    buying_price: 1200,
    sale_price: 1500,
    purchase_quantity: 10,
    product_type: "Electronics",
    shipping_rates: 10,
    refill_limit: 100,
    product_location: "Warehouse A",
  },
  {
    id: 2,
    name: "Smartphone",
    title: "iPhone 13 Pro",
    description:
      "The iPhone 13 Pro is the latest flagship smartphone from Apple, featuring a stunning Super Retina XDR display, powerful A15 Bionic chip, and advanced camera system. Whether you're capturing memories or staying productive on the go, the iPhone 13 Pro delivers unparalleled performance and innovation.",
    vendor: "Apple",
    in_stock: 100,
    buying_price: 1000,
    sale_price: 1200,
    purchase_quantity: 20,
    product_type: "Electronics",
    shipping_rates: 8,
    refill_limit: 150,
    product_location: "Warehouse B",
  },
  {
    id: 3,
    name: "Headphones",
    title: "Sony WH-1000XM4",
    description:
      "Immerse yourself in music like never before with the Sony WH-1000XM4 noise-canceling headphones. With industry-leading noise-canceling technology, premium sound quality, and long-lasting comfort, these headphones are perfect for travel, work, or simply enjoying your favorite tunes at home.",
    vendor: "Sony",
    in_stock: 75,
    buying_price: 250,
    sale_price: 300,
    purchase_quantity: 15,
    product_type: "Electronics",
    shipping_rates: 12,
    refill_limit: 80,
    product_location: "Warehouse C",
  },
  {
    id: 4,
    name: "Camera",
    title: "Canon EOS R5",
    description:
      "Capture every moment with stunning clarity and detail with the Canon EOS R5 mirrorless camera. Equipped with a high-resolution sensor, advanced autofocus system, and 8K video capabilities, the EOS R5 empowers photographers and videographers to push the boundaries of their creativity.",
    vendor: "Canon",
    in_stock: 30,
    buying_price: 3000,
    sale_price: 3500,
    purchase_quantity: 5,
    product_type: "Electronics",
    shipping_rates: 15,
    refill_limit: 50,
    product_location: "Warehouse D",
  },
  {
    id: 5,
    name: "Watch",
    title: "Apple Watch Series 7",
    description:
      "Stay connected, informed, and motivated with the Apple Watch Series 7. Featuring a larger, always-on Retina display, advanced health monitoring features, and fast charging, it's the ultimate companion for a healthy and active lifestyle.",
    vendor: "Apple",
    in_stock: 80,
    buying_price: 400,
    sale_price: 500,
    purchase_quantity: 12,
    product_type: "Electronics",
    shipping_rates: 7,
    refill_limit: 90,
    product_location: "Warehouse E",
  },
  {
    id: 6,
    name: "Tablet",
    title: "Samsung Galaxy Tab S7",
    description:
      "Experience productivity and entertainment in a whole new way with the Samsung Galaxy Tab S7. With its stunning display, powerful performance, and S Pen compatibility, the Tab S7 is perfect for multitasking, creativity, and staying connected on the go.",
    vendor: "Samsung",
    in_stock: 60,
    buying_price: 500,
    sale_price: 600,
    purchase_quantity: 8,
    product_type: "Electronics",
    shipping_rates: 10,
    refill_limit: 70,
    product_location: "Warehouse F",
  },
  {
    id: 7,
    name: "Speaker",
    title: "Sonos One",
    description:
      "Elevate your audio experience with the Sonos One smart speaker. With built-in voice control, multi-room audio capabilities, and rich, immersive sound, the Sonos One is the perfect addition to any home entertainment setup.",
    vendor: "Sonos",
    in_stock: 40,
    buying_price: 150,
    sale_price: 200,
    purchase_quantity: 10,
    product_type: "Electronics",
    shipping_rates: 8,
    refill_limit: 60,
    product_location: "Warehouse G",
  },
  {
    id: 8,
    name: "Backpack",
    title: "North Face Recon",
    description:
      "Designed for durability and comfort, the North Face Recon backpack is built to withstand the rigors of daily life and outdoor adventures. With ample storage space, ergonomic design, and rugged construction, it's the perfect companion for work, school, or travel.",
    vendor: "North Face",
    in_stock: 90,
    buying_price: 80,
    sale_price: 100,
    purchase_quantity: 25,
    product_type: "Accessories",
    shipping_rates: 5,
    refill_limit: 120,
    product_location: "Warehouse H",
  },
  {
    id: 9,
    name: "Printer",
    title: "HP LaserJet Pro",
    description:
      "Print, scan, and copy with ease with the HP LaserJet Pro printer. With fast printing speeds, high-quality results, and seamless connectivity options, it's the ideal solution for busy home offices and small businesses.",
    vendor: "HP",
    in_stock: 50,
    buying_price: 200,
    sale_price: 250,
    purchase_quantity: 10,
    product_type: "Electronics",
    shipping_rates: 10,
    refill_limit: 70,
    product_location: "Warehouse I",
  },
  {
    id: 10,
    name: "Keyboard",
    title: "Logitech G Pro X",
    description:
      "Gain a competitive edge with the Logitech G Pro X mechanical gaming keyboard. Featuring customizable key switches, programmable macros, and durable construction, it's designed to meet the demands of professional gamers and enthusiasts alike.",
    vendor: "Logitech",
    in_stock: 70,
    buying_price: 100,
    sale_price: 150,
    purchase_quantity: 15,
    product_type: "Electronics",
    shipping_rates: 8,
    refill_limit: 80,
    product_location: "Warehouse J",
  },
  {
    id: 11,
    name: "Monitor",
    title: "Dell UltraSharp U2720Q",
    description:
      "Experience stunning visuals and precise color accuracy with the Dell UltraSharp U2720Q monitor. With its 4K resolution and wide color coverage, it's perfect for content creators, designers, and anyone who demands exceptional image quality.",
    vendor: "Dell",
    in_stock: 60,
    buying_price: 600,
    sale_price: 700,
    purchase_quantity: 8,
    product_type: "Electronics",
    shipping_rates: 10,
    refill_limit: 90,
    product_location: "Warehouse K",
  },
  {
    id: 12,
    name: "Fitness Tracker",
    title: "Fitbit Charge 5",
    description:
      "Track your fitness goals and stay motivated with the Fitbit Charge 5. With advanced health monitoring features, built-in GPS, and long battery life, it's the perfect companion for your active lifestyle.",
    vendor: "Fitbit",
    in_stock: 80,
    buying_price: 150,
    sale_price: 200,
    purchase_quantity: 18,
    product_type: "Electronics",
    shipping_rates: 5,
    refill_limit: 100,
    product_location: "Warehouse L",
  },
  {
    id: 13,
    name: "Sneakers",
    title: "Nike Air Zoom Pegasus 38",
    description:
      "Elevate your runs with the Nike Air Zoom Pegasus 38 running shoes. Featuring responsive cushioning, breathable materials, and a secure fit, they're designed to help you go the distance in comfort and style.",
    vendor: "Nike",
    in_stock: 120,
    buying_price: 120,
    sale_price: 150,
    purchase_quantity: 25,
    product_type: "Apparel",
    shipping_rates: 8,
    refill_limit: 150,
    product_location: "Warehouse M",
  },
  {
    id: 14,
    name: "Coffee Machine",
    title: "Nespresso VertuoPlus",
    description:
      "Enjoy barista-quality coffee at home with the Nespresso VertuoPlus coffee machine. With its innovative brewing technology and wide range of coffee options, it's never been easier to indulge in your favorite coffee drinks.",
    vendor: "Nespresso",
    in_stock: 50,
    buying_price: 150,
    sale_price: 200,
    purchase_quantity: 10,
    product_type: "Appliances",
    shipping_rates: 10,
    refill_limit: 80,
    product_location: "Warehouse N",
  },
  {
    id: 15,
    name: "Drone",
    title: "DJI Mavic Air 2",
    description:
      "Capture breathtaking aerial footage with the DJI Mavic Air 2 drone. With its intelligent flight modes, high-resolution camera, and long battery life, it's the perfect tool for aerial photography and videography.",
    vendor: "DJI",
    in_stock: 40,
    buying_price: 800,
    sale_price: 1000,
    purchase_quantity: 5,
    product_type: "Electronics",
    shipping_rates: 20,
    refill_limit: 60,
    product_location: "Warehouse O",
  },
];
